language: node_js

node_js:
- "lts/*"

os:
- linux
- osx
- windows

cache:
  directories:
    - node_modules

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export NPM_CONFIG_PREFIX=c:\\npm_prefix PATH="/c/npm_prefix:$PATH"; fi
  - npm i -g npm@latest

install:
- npm install

script:
- npm test
- npm run lint
- npm run style

notifications:
  email:
    on_success: never
    on_failure: always
