language: node_js

node_js:
- "lts/*"

os:
- linux
- osx

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@latest

install:
- npm install

script:
- npm test
- npm run lint
- npm run style

notifications:
  email:
    on_success: never
    on_failure: always
